willdale/SwiftUICharts

Sources/SwiftUICharts/Shared/Extras/Enums.swift
Sources/SwiftUICharts/Shared/Extras/Extensions.swift
Sources/SwiftUICharts/Shared/Shapes/DiamondShape.swift
Sources/SwiftUICharts/Shared/ViewModifiers/YAxisPOI.swift

Add option to POI markers that allows for the value to be displayed in a label. It can be displayed either in the centre or in the Y Axis labels column.

Add option for POI marker labels.

---

Sources/SwiftUICharts/LineChart/Extras/PathExtensions.swift
Sources/SwiftUICharts/LineChart/Models/LineChartProtocols.swift
Sources/SwiftUICharts/LineChart/Shapes/LineShape.swift
Sources/SwiftUICharts/LineChart/Views/SubViews/LineChartSubViews.swift
Sources/SwiftUICharts/Shared/Models/SharedProtocols.swift
Sources/SwiftUICharts/Shared/ViewModifiers/TouchOverlay.swift

Add a touch or pointer indicator on the lines of the line charts.

V2 - Touch or pointer indicator on line.

---

Sources/SwiftUICharts/BarChart/Models/ChartData/BarChartData.swift
Sources/SwiftUICharts/BarChart/Models/ChartData/GroupedBarChartData.swift
Sources/SwiftUICharts/BarChart/Models/ChartData/RangedBarChartData.swift
Sources/SwiftUICharts/BarChart/Models/ChartData/StackedBarChartData.swift
Sources/SwiftUICharts/SharedLineAndBar/Extras/LineAndBarEnums.swift

Fix x axis label rotation.

---

Sources/SwiftUICharts/BarChart/Models/Style/BarChartStyle.swift
Sources/SwiftUICharts/LineChart/Models/Style/LineChartStyle.swift
Sources/SwiftUICharts/PieChart/Models/Style/DoughnutChartStyle.swift
Sources/SwiftUICharts/PieChart/Models/Style/PieChartStyle.swift
Sources/SwiftUICharts/Shared/Extras/SharedEnums.swift
Sources/SwiftUICharts/Shared/Models/Protocols/SharedProtocols.swift
Sources/SwiftUICharts/Shared/Views/TouchOverlayBox.swift

Hi @willdale ,
I really like the library, even though I use it just for simple usage. But I was blown away by your quick response yesterday, so I want to give something back. Here is a little contribution, that allows to place the infobox content next to each other.
◀️ ▶️

InfoBoxAlignment

---

Sources/SwiftUICharts/BarChart/Models/Style/BarChartStyle.swift
Sources/SwiftUICharts/LineChart/Models/Style/LineChartStyle.swift
Sources/SwiftUICharts/PieChart/Models/Style/DoughnutChartStyle.swift
Sources/SwiftUICharts/PieChart/Models/Style/PieChartStyle.swift
Sources/SwiftUICharts/Shared/Extras/SharedEnums.swift
Sources/SwiftUICharts/Shared/Models/Protocols/SharedProtocols.swift
Sources/SwiftUICharts/Shared/Views/TouchOverlayBox.swift

Adds ability to change info box layout between vertical and horizontal.
Original PR - #46

Info box alignment

---

README.md
Sources/SwiftUICharts/LineChart/ViewModifiers/FilledTopLine.swift
Sources/SwiftUICharts/LineChart/Views/SubViews/LineChartSubViews.swift
Sources/SwiftUICharts/Shared/Shapes/AccessibilityRectangle.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/Protocols/LineAndBarProtocols.swift

Allows for a hard line over the data points with a semi opaque fill.
#47

Add top line to filled line chart

---

Sources/SwiftUICharts/LineChart/Models/ChartData/LineChartData.swift
Sources/SwiftUICharts/LineChart/Models/ChartData/MultiLineChartData.swift
Sources/SwiftUICharts/LineChart/Models/ChartData/RangedLineChartData.swift
Sources/SwiftUICharts/SharedLineAndBar/Views/ YAxisLabelCell.swift

`xAxisLabels` rotation when using `.chartData()`. See #51.

Fix xAxisLabels rotation when using .chartData().

---

Sources/SwiftUICharts/BarChart/Models/Style/BarChartStyle.swift
Sources/SwiftUICharts/LineChart/Models/Style/LineChartStyle.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/Protocols/LineAndBarProtocols.swift
Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/AxisBorders.swift
SwiftUICharts.podspec

Add podspec & x&y Axis border color options

---

README.md
Sources/SwiftUICharts/BarChart/Models/ChartData/HorizontalBarChartData.swift
Sources/SwiftUICharts/BarChart/Views/BarChart.swift
Sources/SwiftUICharts/BarChart/Views/GroupedBarChart.swift
Sources/SwiftUICharts/BarChart/Views/HorizontalBarChart.swift
Sources/SwiftUICharts/BarChart/Views/RangedBarChart.swift
Sources/SwiftUICharts/BarChart/Views/StackedBarChart.swift
Sources/SwiftUICharts/LineChart/Models/ChartData/MultiLineChartData.swift
Sources/SwiftUICharts/LineChart/Models/Protocols/LineChartProtocolsExtensions.swift
Sources/SwiftUICharts/PieChart/Models/Protocols/PieChartProtocolsExtentions.swift
Sources/SwiftUICharts/PieChart/Views/DoughnutChart.swift
Sources/SwiftUICharts/PieChart/Views/PieChart.swift
Sources/SwiftUICharts/Shared/API.swift
Sources/SwiftUICharts/Shared/Models/Protocols/SharedProtocolsExtensions.swift
Sources/SwiftUICharts/Shared/ViewModifiers/HeaderBox.swift
Sources/SwiftUICharts/Shared/Views/LegendView.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/Protocols/LineAndBarProtocolsExtentions.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/Protocols/PointOfInterestProtocol.swift
Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/XAxisPOI.swift
Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/YAxisPOI.swift
Sources/SwiftUICharts/SharedLineAndBar/Views/RotatedText.swift

- Localization within the charts. See #96
- Localization support for VoiceOver.

Add Localization support

---

README.md
Sources/SwiftUICharts/BarChart/Models/ChartData/BarChartData.swift
Sources/SwiftUICharts/BarChart/Models/ChartData/GroupedBarChartData.swift
Sources/SwiftUICharts/BarChart/Models/ChartData/HorizontalBarChartData.swift
Sources/SwiftUICharts/BarChart/Models/ChartData/RangedBarChartData.swift
Sources/SwiftUICharts/BarChart/Models/ChartData/StackedBarChartData.swift
Sources/SwiftUICharts/LineChart/Models/ChartData/LineChartData.swift
Sources/SwiftUICharts/LineChart/Models/ChartData/MultiLineChartData.swift
Sources/SwiftUICharts/LineChart/Models/ChartData/RangedLineChartData.swift
Sources/SwiftUICharts/Shared/Models/ColourStyle.swift
Sources/SwiftUICharts/Shared/Models/Protocols/SharedProtocolsExtensions.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/ExtraLineData.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/ExtraLineDataPoint.swift
Sources/SwiftUICharts/SharedLineAndBar/Shapes/ExtraLineShape.swift
Sources/SwiftUICharts/SharedLineAndBar/Style/ExtraLineStyle.swift
Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/ExtraLine.swift
SwiftUICharts.podspec

Adds point markers to `.extraLine`. See #104.

Add extra point markers

---

Sources/SwiftUICharts/SharedLineAndBar/Models/ChartViewData.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/Protocols/LineAndBarProtocolsExtentions.swift
Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/YAxisLabels.swift

- More control over the formatting of numeric Y axis labels. See #130

Add number formatter for Y axis labels.

---

Sources/SwiftUICharts/Shared/Models/Protocols/SharedProtocolsExtensions.swift

- See [comment](https://github.com/willdale/SwiftUICharts/issues/133#issuecomment-965637891) in #133

Fix baseline in multi line line chart when using ignore zero.

---

Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/ExtraLine.swift

Fix a bug where extra line legends could be added multiple times.

Ensure that extra line legends can't be added multiple times.

---

Sources/SwiftUICharts/LineChart/Extras/LineChartEnums.swift
Sources/SwiftUICharts/LineChart/Extras/PathExtensions.swift
Sources/SwiftUICharts/LineChart/Models/Protocols/LineChartProtocolsExtensions.swift
Sources/SwiftUICharts/LineChart/Shapes/LineShape.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/ExtraLineData.swift
Sources/SwiftUICharts/SharedLineAndBar/Shapes/ExtraLineShape.swift

Added support for Stepped Line Style for stepped style charts. #164

Added Stepped Line Style

---

Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/ExtraLine.swift

Fixed issue where extraline skipped passed in stroke style

---

Sources/SwiftUICharts/SharedLineAndBar/Views/RotatedText.swift

XAxis Label Height distortion fix

---

Sources/SwiftUICharts/SharedLineAndBar/Views/RotatedText.swift

Reverts willdale/SwiftUICharts#175 which reverts a revert...
Initial PR willdale/SwiftUICharts#167 -> possible issue raised willdale/SwiftUICharts#174 -> Reverted PR willdale/SwiftUICharts#175
Also raised in willdale/SwiftUICharts#185

Revert "Revert "XAxis Label Height distortion fix""

---

Sources/SwiftUICharts/BarChart/Views/StackedBarChart.swift
Sources/SwiftUICharts/BarChart/Views/SubViews/BarChartSubViews.swift
Sources/SwiftUICharts/BarChart/Views/SubViews/Bars.swift

191: Fix redrawing of bar chart when data changes

---

Sources/SwiftUICharts/LineChart/Models/ChartData/LineChartData.swift

View weren't updating on `dataPoints` change inside `GeometryReader`

Fixed X axis labels live updating

---

Sources/SwiftUICharts/SharedLineAndBar/Models/ExtraLineData.swift
Sources/SwiftUICharts/SharedLineAndBar/Models/Protocols/LineAndBarProtocolsExtentions.swift
Tests/SwiftUIChartsTests/BarCharts/BarChartTests.swift
Tests/SwiftUIChartsTests/BarCharts/GroupedBarChartTests.swift
Tests/SwiftUIChartsTests/BarCharts/StackedBarChartTests.swift
Tests/SwiftUIChartsTests/LineCharts/LineChartTests.swift
Tests/SwiftUIChartsTests/LineCharts/MultiLineChartTest.swift

Fixes issue for main line, not extra line.

206: Fix drawing for smaller numbers.
